### ISSUE TITLE
Your change from original repositories to custom repositories

### ISSUE THREAD

**Issue by araeubig** [Automattic/vip-codespaces#35]
I saw that you changed all sources to custom repositories. Why you did this? I hoped for an outstanding version but actually i saw customized images in all container files. No the "repository" logic is gone away - but perhaps you have done this to be more stable? But now no one could see the real source of the images. I am very interested in your final working solution.

**Comment by sjinks** [comment]
I am afraid I don't understand the question...

I have three images at the moment:
* alpine-base: the lightweight image with `runsvc` and packages VSCode expects
* wordpress-all-in-one: based on alpine-base, it adds php, mysql, memcached, mailpit, nginx
* wordpress-all-in-one-xdebug: based on wordpress-all-in-one, adds xdebug (I did not include xdebug in wordpress-all-in-one because it significantly slows PHP requests).

All those images are stored in `ghcr.io` container registry - this is where `devcontainers` CLI utility pushes them by default.

**Comment by sjinks** [comment]
`ghcr.io/automattic/vip-codespaces/alpine-base`:
* ghcr.io - container registry
* automattic/vip-codespaces - repository - https://github.com/automattic/vip-codespaces
* alpine-base - image name; the image is generated from a Dockerfile in the repo.

Moreover, you can always see the source with `docker history image-name`.

**Comment by sjinks** [comment]
This repository (https://github.com/Automattic/vip-codespaces): it is designed to work with [Automattic/vip-go-skeleton](https://github.com/Automattic/vip-go-skeleton/tree/dev-containers-with-tons-of-features) on the WordPress VIP platform.

My personal repository (https://github.com/sjinks/codespaces): it contains generic WordPress images.
